pipeline {

	agent any
	environment {
        // This can be nexus3 or nexus2
    //    NEXUS_VERSION = "nexus3"
        // This can be http or https
   //     NEXUS_PROTOCOL = "http"
        // Where your Nexus is running
    //    NEXUS_URL = "192.168.222.135:8081"
        // Repository where we will upload the artifact
   //     NEXUS_REPOSITORY = "Releases"
        // Jenkins credential id to authenticate to Nexus OSS
  //      NEXUS_CREDENTIAL_ID = "admin:admin123"
    }
    
     stages {
        

	stage("Verification du version Maven") {
           steps {
                sh "mvn -version"
              
            }

        }
	
       stage("Supprimer le contenu du dossier target") {
            steps {
                script {
                    //this step attempts to clean the files and directories generated by Maven during its build
                    sh "mvn clean"
		  }
            }
        }
	
	stage ("Creation du livrable"){
			steps{
				sh "mvn package"
			}
		} 
	
	

	  
}
}
